### ISSUE TITLE
这个有点太危险了吧。。

### ISSUE THREAD

**Issue by dev-techmoe** [coderfox/LLMCG#1]
爆破别人api见光死这个道理懂吗。。  
如果被很多其他人发现，大规模恶意调用api 说不定哪天不许摸方面直接升级相关function，然后就233了  
之前云音乐和百度云等一些东西api被爆破后都出现过这种情况，如果这种东西大范围暴露出去再被一群人恶意调用我不相信不许摸方面一点措施也没有  
同时也可能催生出一批诸如脚本打活动之类的毫无意义的人。。  
7月5号又要大更这一点也知道吧，，希望别在这上面出什么问题。。

**Comment by coderfox** [comment]
这里没带上最重要的 key。所以直接拿来没法用。

发 API 这种事也不是我第一个干的。

**Comment by dev-techmoe** [comment]
尽量控制

**Comment by coderfox** [comment]
算了这玩意也没啥用，我还是转私有吧。

Closed。
